name: .NET

on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    steps:
    - uses: actions/checkout@v2.3.4
        
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0'
        
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release "SharedLoaderNet"
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SharedLoaderNet
        path: SharedLoaderNet/Release
