name: .NET

on: [push, pull_request]

jobs:
  test:
    name: .Net ${{ matrix.dotnet }} with ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        framework: ['net48', 'netcoreapp3.1', 'net5.0']
        include: 
          - framework: 'net48'
            dotnet: '5.0'
          - framework: 'netcoreapp3.1'
            dotnet: '3.1'
          - framework: 'net5.0'
            dotnet: '5.0'
        exclude:
         - os: ubuntu-latest
           framework: 'net48'
         - os: macos-latest
           framework: 'net48'
    timeout-minutes: 30
    
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    steps:
    - uses: actions/checkout@v2.3.4
        
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet }}
        
    - name: Test ${{ matrix.framework }}
      run: dotnet test --framework ${{ matrix.framework }}
